@base-url = http://localhost:8000/api/v1
### GET request to example server

GET http://localhost:8000/test/products
Authorization: basic

### GET Owners
GET {{base-url}}/owners/

### Add new Owner
POST {{base-url}}/owners/
content-type: application/json

  {
    "first_name": "test-2",
    "last_name": "Owner-2",
    "email": "testing2@gmail.com",
    "phone_number": "0788001123"
  }

### GET Properties

GET {{base-url}}/properties/
