# Generated by Django 5.1.2 on 2024-10-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalagreement",
            name="contact_file",
            field=models.FileField(blank=True, null=True, upload_to="agreements/"),
        ),
    ]
