# Generated by Django 5.1.2 on 2024-10-14 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_rentalagreement_contact_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "Property", "verbose_name_plural": "Properties"},
        ),
    ]
