# Generated by Django 5.1.2 on 2024-10-21 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_property_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
    ]
